# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AWIPS II User Guide
email: support-awips@unidata.ucar.edu
description: > # this means to ignore newlines until "baseurl:"
  AWIPS II is a weather forecasting display and analysis package being developed 
  by the National Weather Service and Raytheon. AWIPS II is a Java application 
  consisting of a data-rendering client (CAVE) and a backend data server (EDEX), 
  and incorporates open source technologies such as HDF5, Qpid, Postgres and PyPIES.
baseurl: "/awips2" # the subpath of your site, e.g. /blog
url: "http://unidata.github.io" # the base hostname & protocol for your site
github_username:  Unidata

# Build settings
markdown: kramdown
